// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/home.vue')['default']
    QueryEditorCard: typeof import('./src/components/panel/QueryEditorCard.vue')['default']
    ResultPreviewCard: typeof import('./src/components/panel/ResultPreviewCard.vue')['default']
  }
}

export {}
