/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./components/home.vue')['default']
    QueryEditorCard: typeof import('./components/panel/QueryEditorCard.vue')['default']
    ResultPreviewCard: typeof import('./components/panel/ResultPreviewCard.vue')['default']
  }
}
